### ISSUE TITLE
Failed deploy at Bitcoin daemon banlist importer

### ISSUE THREAD

**Issue by alessandro-saglimbeni** [fort-nix/nix-bitcoin#122]
After modifying the dbcache in modules/nix-bitcoin.nix
from `    services.bitcoind.dbCache = 4000;` 
to `    services.bitcoind.dbCache = 6000;`

`nixops deploy -d bitcoin-node` fails:

```
[nix-shell:~/nix-bitcoin]$ nixops deploy -d bitcoin-node
building all machine configurations...
bitcoin-node> copying closure...
bitcoin-node> closures copied successfully
bitcoin-node> uploading key ‘bitcoin-rpcpassword’...
bitcoin-node> uploading key ‘spark-wallet-login’...
bitcoin-node> uploading key ‘liquid-rpcpassword’...
bitcoin-node> updating GRUB 2 menu...
bitcoin-node> activating the configuration...
bitcoin-node> setting up /etc...
bitcoin-node> reloading user units for root...
bitcoin-node> setting up tmpfiles
bitcoin-node> warning: the following units failed: bitcoind-import-banlist.service
bitcoin-node> 
bitcoin-node> ● bitcoind-import-banlist.service - Bitcoin daemon banlist importer
bitcoin-node>    Loaded: loaded (/nix/store/8wghr967ycyxj868z3q3slljw1nm7a1g-unit-bitcoind-import-banlist.service/bitcoind-import-banlist.service; enabled; vendor preset: enabled)
bitcoin-node>    Active: failed (Result: timeout) since Thu 2019-10-10 16:43:50 UTC; 2s ago
bitcoin-node>   Process: 10606 ExecStartPre=/nix/store/b3hj3cmsdr7fz1vjrn594zg7m0syq9nv-unit-script-bitcoind-import-banlist-pre-start (code=killed, signal=TERM)
bitcoin-node>  Main PID: 15858 (code=exited, status=0/SUCCESS)
bitcoin-node> 
bitcoin-node> Oct 10 16:43:47 cube-nix-bitcoin b3hj3cmsdr7fz1vjrn594zg7m0syq9nv-unit-script-bitcoind-import-banlist-pre-start[10606]: Loading block index...
bitcoin-node> Oct 10 16:43:48 cube-nix-bitcoin b3hj3cmsdr7fz1vjrn594zg7m0syq9nv-unit-script-bitcoind-import-banlist-pre-start[10606]: error code: -28
bitcoin-node> Oct 10 16:43:48 cube-nix-bitcoin b3hj3cmsdr7fz1vjrn594zg7m0syq9nv-unit-script-bitcoind-import-banlist-pre-start[10606]: error message:
bitcoin-node> Oct 10 16:43:48 cube-nix-bitcoin b3hj3cmsdr7fz1vjrn594zg7m0syq9nv-unit-script-bitcoind-import-banlist-pre-start[10606]: Loading block index...
bitcoin-node> Oct 10 16:43:50 cube-nix-bitcoin b3hj3cmsdr7fz1vjrn594zg7m0syq9nv-unit-script-bitcoind-import-banlist-pre-start[10606]: error code: -28
bitcoin-node> Oct 10 16:43:50 cube-nix-bitcoin b3hj3cmsdr7fz1vjrn594zg7m0syq9nv-unit-script-bitcoind-import-banlist-pre-start[10606]: error message:
bitcoin-node> Oct 10 16:43:50 cube-nix-bitcoin b3hj3cmsdr7fz1vjrn594zg7m0syq9nv-unit-script-bitcoind-import-banlist-pre-start[10606]: Loading block index...
bitcoin-node> Oct 10 16:43:50 cube-nix-bitcoin systemd[1]: bitcoind-import-banlist.service: Start-pre operation timed out. Terminating.
bitcoin-node> Oct 10 16:43:50 cube-nix-bitcoin systemd[1]: bitcoind-import-banlist.service: Failed with result 'timeout'.
bitcoin-node> Oct 10 16:43:50 cube-nix-bitcoin systemd[1]: Failed to start Bitcoin daemon banlist importer.
bitcoin-node> error: Traceback (most recent call last):
  File "/nix/store/jln9i6pa2544wqnjybh0wm3w587zxqm3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 743, in worker
    raise Exception("unable to activate new configuration (exit code {})".format(res))
Exception: unable to activate new configuration (exit code 4)

Traceback (most recent call last):
  File "/nix/store/jln9i6pa2544wqnjybh0wm3w587zxqm3-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/jln9i6pa2544wqnjybh0wm3w587zxqm3-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/jln9i6pa2544wqnjybh0wm3w587zxqm3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/jln9i6pa2544wqnjybh0wm3w587zxqm3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/jln9i6pa2544wqnjybh0wm3w587zxqm3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/jln9i6pa2544wqnjybh0wm3w587zxqm3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1019, in _deploy
    dry_activate=dry_activate, max_concurrent_activate=max_concurrent_activate)
  File "/nix/store/jln9i6pa2544wqnjybh0wm3w587zxqm3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 775, in activate_configs
    .format(len(failed), len(res), ", ".join(["‘{0}’".format(x) for x in failed])))
Exception: activation of 1 of 1 machines failed (namely on ‘bitcoin-node’)
```

**Comment by jonasnick** [comment]
Thanks for the bug report, I've seen it a couple of times, but was too lazy so far to fix it. The problem is that bitcoind isn't "warmed up" when trying to import the banlist (`error message: Loading block index...`). The operation of bitcoind and the rest of the system should be unaffected despite the nixops exception.
