### ISSUE TITLE
Deployment failed while migrating to v0.0.1

### ISSUE THREAD

**Issue by alessandro-saglimbeni** [fort-nix/nix-bitcoin#172]
At step 6. of the migration guide in the v0.0.1 release notes, after deploying I get the following error.

Any hint at what I may have done wrong while migrating to the new upgrade process?
```
$ nixops deploy --show-trace
warning: ignoring the user-specified setting 'show-trace', because it is a restricted setting and you are not a trusted user
warning: ignoring the user-specified setting 'show-trace', because it is a restricted setting and you are not a trusted user
error: while evaluating the attribute 'config.deployment' at undefined position:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/options.nix:177:41, called from undefined position:
while evaluating 'scrubOptionValue' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/options.nix:173:22, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/options.nix:177:44:
while evaluating 'isDerivation' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/attrsets.nix:305:18, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/options.nix:174:8:
while evaluating the attribute 'config' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:96:25:
while evaluating 'yieldConfig' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:83:29, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:82:16:
while evaluating 'mergeModules' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:233:26, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:73:17:
while evaluating 'mergeModules'' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:237:36, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:234:5:
while evaluating 'flip' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/trivial.nix:138:16, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:280:6:
while evaluating 'byName' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:260:25, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:268:21:
while evaluating 'reverseList' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/lists.nix:393:17, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:73:38:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:167:37, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:68:19:
while evaluating 'filterModules' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:157:36, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:168:7:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:161:31, called from undefined position:
while evaluating the attribute 'disabled' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:139:13:
while evaluating the attribute 'disabled' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:139:13:
while evaluating the attribute 'disabled' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:139:13:
while evaluating 'loadModule' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:106:53, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:144:22:
while evaluating 'unifyModuleSyntax' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:172:34, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:109:14:
while evaluating 'applyIfFunction' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:198:29, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:109:59:
while evaluating 'isFunction' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/trivial.nix:333:16, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:198:68:
syntax error, unexpected '}', expecting ';', at /nix/store/wgzmgh3cpv04vfg8ca8w9hygc7sa5dck-nix-bitcoin-src/modules/nix-bitcoin.nix:9:1
error: evaluation of the deployment specification failed
```

**Comment by erikarvstedt** [comment]
You can fix this in your config by importing `<nix-bitcoin/modules/presets/secure-node.nix>` instead of `<nix-bitcoin/modules/nix-bitcoin.nix>`.

**Comment by alessandro-saglimbeni** [comment]
I have my HEAD on top of b9fbb144cae9aa8c8d7ebe143ac02c3b1e15651d as per the migration guide, do you recommend me to rebase on top of master or some other tag, and then applying your fix? 

I'm asking because I don't have `<nix-bitcoin/modules/presets/secure-node.nix>` and I get the following error when deploying after changing the modules imported in the config

```bash
$ nixops deploy --show-trace
warning: ignoring the user-specified setting 'show-trace', because it is a restricted setting and you are not a trusted user
warning: ignoring the user-specified setting 'show-trace', because it is a restricted setting and you are not a trusted user
building all machine configurations...
warning: ignoring the user-specified setting 'show-trace', because it is a restricted setting and you are not a trusted user
error: while evaluating the attribute 'buildCommand' of the derivation 'nixops-machines' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating anonymous function at /nix/store/mkfsk23sl0mfjv1md3xlnmawdckwqd2m-nixops-1.8pre0_abcdef/share/nix/nixops/eval-machine-info.nix:167:46, called from undefined position:
while evaluating the attribute 'config.system.build.toplevel' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/nixos/modules/system/activation/top-level.nix:275:5:
while evaluating 'foldr' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/lists.nix:52:20, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/nixos/modules/system/activation/top-level.nix:139:12:
while evaluating 'fold'' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/lists.nix:55:15, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/lists.nix:59:8:
while evaluating the attribute 'assertions' at undefined position:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:84:45, called from undefined position:
while evaluating the attribute 'value' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:379:9:
while evaluating the option `assertions':
while evaluating the attribute 'mergedValue' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:411:5:
while evaluating the attribute 'values' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:405:9:
while evaluating the attribute 'values' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:505:7:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:391:28, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:391:17:
while evaluating 'dischargeProperties' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:464:25, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:392:62:
while evaluating the attribute 'value' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:277:44:
while evaluating 'flip' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/trivial.nix:138:16, called from /nix/store/mkfsk23sl0mfjv1md3xlnmawdckwqd2m-nixops-1.8pre0_abcdef/share/nix/nixops/keys.nix:179:18:
while evaluating 'mapAttrsToList' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/attrsets.nix:233:23, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/trivial.nix:138:19:
while evaluating the attribute 'deployment.keys' at undefined position:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:84:45, called from undefined position:
while evaluating the attribute 'value' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:379:9:
while evaluating the option `deployment.keys':
while evaluating the attribute 'mergedValue' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:411:5:
while evaluating the attribute 'values' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:405:9:
while evaluating the attribute 'values' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:505:7:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:391:28, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:391:17:
while evaluating 'dischargeProperties' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:464:25, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:392:62:
while evaluating the attribute 'value' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:277:44:
while evaluating the attribute 'nix-bitcoin.secrets' at undefined position:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:84:45, called from undefined position:
while evaluating the attribute 'value' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:379:9:
while evaluating the option `nix-bitcoin.secrets':
while evaluating the attribute 'mergedValue' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:411:5:
while evaluating the attribute 'values' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:405:9:
while evaluating the attribute 'values' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:505:7:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:391:28, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:391:17:
while evaluating 'dischargeProperties' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:464:25, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:392:62:
while evaluating the attribute 'condition' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:549:14:
while evaluating the attribute 'condition' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:549:14:
while evaluating the attribute 'condition' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:549:14:
while evaluating the attribute 'services.lnd' at undefined position:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:84:45, called from undefined position:
while evaluating 'yieldConfig' at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:83:29, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:86:16:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:89:24, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:89:11:
while evaluating anonymous function at /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:90:26, called from /nix/store/j5nzal9kpz06bqx73gzqskzjcba43ba3-source/lib/modules.nix:90:13:
The option `services.nix-bitcoin' defined in `/home/alessandro/my-nix-bitcoin/configuration.nix' does not exist.
Traceback (most recent call last):
  File "/nix/store/mkfsk23sl0mfjv1md3xlnmawdckwqd2m-nixops-1.8pre0_abcdef/bin/.nixops-wrapped", line 251, in <module>
    args.op(args)
  File "/nix/store/mkfsk23sl0mfjv1md3xlnmawdckwqd2m-nixops-1.8pre0_abcdef/lib/python2.7/site-packages/nixops/script_defs.py", line 427, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/mkfsk23sl0mfjv1md3xlnmawdckwqd2m-nixops-1.8pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1062, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/mkfsk23sl0mfjv1md3xlnmawdckwqd2m-nixops-1.8pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1051, in run_with_notify
    f()
  File "/nix/store/mkfsk23sl0mfjv1md3xlnmawdckwqd2m-nixops-1.8pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1062, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/mkfsk23sl0mfjv1md3xlnmawdckwqd2m-nixops-1.8pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 1006, in _deploy
    self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/mkfsk23sl0mfjv1md3xlnmawdckwqd2m-nixops-1.8pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 674, in build_configs
    raise Exception("unable to build all machine configurations")
Exception: unable to build all machine configurations
```

Sorry I'm learning here, in general is it a bad idea for me to go to `/nix/store/wgzmgh3cpv04vfg8ca8w9hygc7sa5dck-nix-bitcoin-src/modules/nix-bitcoin.nix` and fix myself like in https://github.com/fort-nix/nix-bitcoin/pull/173? My understanding is that I'm not supposed to ever touch any of those store files right?

**Comment by erikarvstedt** [comment]
1. Use one of the lastest releases. https://github.com/fort-nix/nix-bitcoin/commit/b9fbb144cae9aa8c8d7ebe143ac02c3b1e15651d is outdated.

2. In `configuration.nix`:
    - Import `presets/secure-node.nix`, as described above.  
    - Delete the line `services.nix-bitcoin.enable = true;`

**Comment by nixbitcoin** [comment]
Reopening because we need to make it easier to deal with updates to `configuration.nix`

**Comment by erikarvstedt** [comment]
@nixbitcoin, what do you think is the remaining issue?

My instructions were a specific workaround for the bug that has now been fixed.

**Comment by nixbitcoin** [comment]
I don't like the way configuration.nix has to be manually edited for any new features or fixes to it. So I wanted to leave the issue open to remind me that I need to work on that. But I'll close it and open a new, more specific one.
