### ISSUE TITLE
Neither 'text' or 'keyFile' options were set for key 'bitcoin-HMAC-public' error

### ISSUE THREAD

**Issue by galderz** [fort-nix/nix-bitcoin#277]
Still struggling to get nix-bitcoin deployed on another node :(

This time I'm getting `Neither 'text' or 'keyFile' options were set for key 'bitcoin-HMAC-public'.` error. What is this about? These keys have been generated in `secrets/` folder...

```
bitcoin-node> closures copied successfully
bitcoin-node> uploading key ‘bitcoin-HMAC-public’...
bitcoin-node> error: Traceback (most recent call last):
  File "/nix/store/hgjbp45ag4xy5yv95iaqp90g692d68n3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 727, in worker
    m.send_keys()
  File "/nix/store/hgjbp45ag4xy5yv95iaqp90g692d68n3-nixops-1.7/lib/python2.7/site-packages/nixops/backends/__init__.py", line 234, in send_keys
    raise Exception("Neither 'text' or 'keyFile' options were set for key '{0}'.".format(k))
Exception: Neither 'text' or 'keyFile' options were set for key 'bitcoin-HMAC-public'.

Traceback (most recent call last):
  File "/nix/store/hgjbp45ag4xy5yv95iaqp90g692d68n3-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/hgjbp45ag4xy5yv95iaqp90g692d68n3-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/hgjbp45ag4xy5yv95iaqp90g692d68n3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/hgjbp45ag4xy5yv95iaqp90g692d68n3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/hgjbp45ag4xy5yv95iaqp90g692d68n3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/hgjbp45ag4xy5yv95iaqp90g692d68n3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1019, in _deploy
    dry_activate=dry_activate, max_concurrent_activate=max_concurrent_activate)
  File "/nix/store/hgjbp45ag4xy5yv95iaqp90g692d68n3-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 775, in activate_configs
    .format(len(failed), len(res), ", ".join(["‘{0}’".format(x) for x in failed])))
Exception: activation of 1 of 1 machines failed (namely on ‘bitcoin-node’)
```

**Comment by galderz** [comment]
I don't know what happened there, I've recreated nix-bitcoin-node from scratch and start `nix-shell` from the initial `nix-shell` that was started from `examples` and that seemed to have gone further...

```
bitcoin-node> closures copied successfully
bitcoin-node> uploading key ‘bitcoin-HMAC-privileged’...
bitcoin-node> uploading key ‘bitcoin-rpcpassword-public’...
bitcoin-node> uploading key ‘bitcoin-HMAC-public’...
bitcoin-node> uploading key ‘bitcoin-rpcpassword-privileged’...
...
```

**Comment by galderz** [comment]
Now having issue https://github.com/fort-nix/nix-bitcoin/issues/278 :\

**Comment by galderz** [comment]
Recreated node configuration and then it worked.
