### ISSUE TITLE
joinmarket-yieldgenerator _DEFAULT_INTEREST_RATE error

### ISSUE THREAD

**Issue by alumbigi** [fort-nix/nix-bitcoin#439]
After I added a fidelity bond, joinmarket-yieldgenerator throws an error on startup that looks like this:

```
Unhandled error in Deferred:
Traceback (most recent call last):
  File "/nix/store/.../python3.9/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/nix/store/.../python3.9/site-packages/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
  File "/nix/store/.../python3.9/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/nix/store/.../python3.9/site-packages/twisted/internet/task.py", line 253, in __call__
    d = maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/nix/store/.../python3.9/site-packages/twisted/internet/defer.py", line 191, in maybeDeferred
    result = f(*args, **kwargs)
  File "/nix/store/.../python3.9/site-packages/jmclient/maker.py", line 48, in try_to_create_my_orders
    self.fidelity_bond = self.get_fidelity_bond_template()
  File "/nix/store/.../python3.9/site-packages/jmclient/yieldgenerator.py", line 154, in get_fidelity_>
    interest_rate = get_interest_rate()
  File "/nix/store/.../python3.9/site-packages/jmclient/configure.py", line 587, in get_interest_rate
    return float(global_singleton.config.get('POLICY', 'interest_rate',
builtins.ValueError: could not convert string to float: '""" + _DEFAULT_INTEREST_RATE + """'
```
to fix it, I edited the file `/var/lib/joinmarket/joinmarket.cfg`
replaced `“”” + _DEFAULT_INTEREST_RATE + “””` with `0.015`
and restarted joinmarket-yieldgenerator

Notes:
 - if I restart joinmarket, my edit get reversed
 - NixOS 21.11, nix-bitcoin 0.0.60 and 0.0.61
 - I am trying to learn how to code and test a change that adds the ability to set something like services.joinmarket.interestrate in configuration.nix. I am not there yet
 - thanks

**Comment by nixbitcoin** [comment]
Thank you for bringing this to our attention. First of all, `joinmarket.cfg` resets on every restart since it is copied from the `/nix/store` config specified in https://github.com/fort-nix/nix-bitcoin/blob/ed42834a883532562cca4a05aee7caa0e1de3093/modules/joinmarket.nix#L172.

Since the error resulted from my mistake, I will fix this issue shortly.

> * I am trying to learn how to code and test a change that adds the ability to set something like services.joinmarket.interestrate in configuration.nix. I am not there yet

That would be very helpful.
