### ISSUE TITLE
Cannot do remote duplicity backups

### ISSUE THREAD

**Issue by tim-tx** [fort-nix/nix-bitcoin#470]
I have a backup config that started failing on March 2 after working for several months. I have generally updated/deployed nix-bitcoin within a few days of a new release.

The failure logs look like:
```
Mar 09 00:00:05 nixos systemd[1]: Started backup files with duplicity.
Mar 09 00:00:05 nixos duplicity-start[19552]: + /nix/store/3wbnrkbsg8279m1gvq8visq67lnkifyv-duplicity-0.8.20/bin/duplicity cleanup sftp://myremotemachine/nix-bitcoin --force --archive-dir /var/lib/duplicity --include-filelist /nix/store/c5n4arqrfhr3y42ypw6qd6wxby79lwxx-filelist.txt
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh: Unknown exception: q must be exactly 160, 224, or 256 bits long
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh: Traceback (most recent call last):
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:   File "/nix/store/w1crdvfn0iyz6madi8zk8r6k6csx5wpp-python3.9-paramiko-2.7.2/lib/python3.9/site-packages/paramiko/transport.py", line 2109, in run
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:     handler(self.auth_handler, m)
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:   File "/nix/store/w1crdvfn0iyz6madi8zk8r6k6csx5wpp-python3.9-paramiko-2.7.2/lib/python3.9/site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:     sig = self.private_key.sign_ssh_data(blob)
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:   File "/nix/store/w1crdvfn0iyz6madi8zk8r6k6csx5wpp-python3.9-paramiko-2.7.2/lib/python3.9/site-packages/paramiko/dsskey.py", line 108, in sign_ssh_data
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:     key = dsa.DSAPrivateNumbers(
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:   File "/nix/store/jcfmz342p7iab56r8f7y8p42x25pfkyz-python3.9-cryptography-3.4.8/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 244, in private_key
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:     return backend.load_dsa_private_numbers(self)
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:   File "/nix/store/jcfmz342p7iab56r8f7y8p42x25pfkyz-python3.9-cryptography-3.4.8/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 826, in load_dsa_private_numbers
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:     dsa._check_dsa_private_numbers(numbers)
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:   File "/nix/store/jcfmz342p7iab56r8f7y8p42x25pfkyz-python3.9-cryptography-3.4.8/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 282, in _check_dsa_private_numbers
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:     _check_dsa_parameters(parameters)
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:   File "/nix/store/jcfmz342p7iab56r8f7y8p42x25pfkyz-python3.9-cryptography-3.4.8/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 274, in _check_dsa_parameters
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:     raise ValueError("q must be exactly 160, 224, or 256 bits long")
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh: ValueError: q must be exactly 160, 224, or 256 bits long
Mar 09 00:00:08 nixos duplicity-start[19553]: ssh:
Mar 09 00:00:08 nixos duplicity-start[19553]: BackendException: ssh connection to mynixbitcoinuser@123.45.67.89:34567 failed: q must be exactly 160, 224, or 256 bits long
Mar 09 00:00:09 nixos systemd[1]: duplicity.service: Main process exited, code=exited, status=23/n/a
Mar 09 00:00:09 nixos systemd[1]: duplicity.service: Failed with result 'exit-code'.
Mar 09 00:00:09 nixos systemd[1]: duplicity.service: Consumed 2.188s CPU time, received 2.1K IP traffic, sent 3.0K IP traffic.
```

Relevant part of my nix config is:

```
  services.backups.enable = true;
  services.backups.destination = "sftp://myremotemachine/nix-bitcoin";
  programs.ssh.knownHosts."myremotemachine" = {
    hostNames = [ "myremotemachine" "[123.45.67.89]:34567" ];
    publicKey = "<redacted>";
  };
  programs.ssh.extraConfig = ''
    Host myremotemachine
        HostName 123.45.67.89
        User mynixbitcoinuser
        Port 34567
        IdentityFile ${config.nix-bitcoin.secretsDir}/backup-ssh-private-key
  '';
  nix-bitcoin.secrets = {
    backup-ssh-private-key.permissions = "400";
  };
  services.backups.with-bulk-data = false;
```

The ssh key was generated with:
```
ssh-keygen -t rsa -b 4096 -C "nix-bitcoin backup"
```

From the log, it looks like the key is being interpreted as a DSA key. There's a closed [upstream bug](https://github.com/paramiko/paramiko/issues/1590#issuecomment-573107144) in paramiko with the same failure. The linked comment says basically "it's probably a bug, just use the `paramiko.RSAKey` constructor."

Anyway I'm asking about this here because [the version of paramiko (2.7.2, see logs) installed by nix-bitcoin](https://github.com/paramiko/paramiko/releases/tag/2.7.2) seems to be very old, from 2020. I'm a nix noob but I suppose I could try to run with newer versions in a separate environment to see if that works.

I haven't seen any way of specifying in `ssh_config` or duplicity that the key should be interpreted as RSA. There's a "legacy" ssh backend for duplicity called pexpect, but I haven't been able to make this work. Probably not setting it up correctly.
```
  environment.systemPackages = with pkgs; [
    python3Packages.pexpect
  ];
  services.backups.destination = "pexpect+sftp://myremotemachine/nix-bitcoin";
```
Results in:
```
Mar 30 15:18:54 nixos systemd[1]: Started backup files with duplicity.
Mar 30 15:18:54 nixos duplicity-start[32049]: + /nix/store/3wbnrkbsg8279m1gvq8visq67lnkifyv-duplicity-0.8.20/bin/duplicity cleanup pexpect+sftp://myremotemachine/nix-bitcoin --force --archive-dir /var/lib/duplicity --include-filelist /nix/store/c5n4arqrfhr3y42ypw6qd6wxby79lwxx-filelist.txt
Mar 30 15:18:55 nixos duplicity-start[32050]: BackendException: Could not initialize backend: No module named 'pexpect'
Mar 30 15:18:55 nixos systemd[1]: duplicity.service: Main process exited, code=exited, status=23/n/a
Mar 30 15:18:55 nixos systemd[1]: duplicity.service: Failed with result 'exit-code'.
Mar 30 15:18:55 nixos systemd[1]: duplicity.service: Consumed 1.082s CPU time, no IP traffic.
```

**Comment by tim-tx** [comment]
There are other paramiko PRs and bugs:
https://github.com/paramiko/paramiko/pull/1606  (user reports paramiko v2.8.1 working, but not v2.9.2)
https://github.com/paramiko/paramiko/pull/1993
https://github.com/paramiko/paramiko/issues/1839

**Comment by tim-tx** [comment]
I got the pexpect backend to work with the following config:
```
  nixpkgs.overlays = [(self: super: {
    duplicity = super.duplicity.overrideAttrs (oldAttrs: {
      pythonPath = oldAttrs.pythonPath ++ [ pkgs.python3.pkgs.pexpect pkgs.openssh ];
    });
  })];
  services.backups.destination = "pexpect+sftp://myremotemachine/nix-bitcoin";
```
