### ISSUE TITLE
VirtualBox Image (50GB) is to small for the Bitcoin Blockchain

### ISSUE THREAD

**Issue by 0xB10C** [fort-nix/nix-bitcoin#50]
**Problem**
Setting up a nix-bitcoin node in VirtualBox with the provided manual in `docs/install.md` creates a VirtualBox image with only 50GB of disk space. The Bitcoin blockchain needs more space.

**Reproduce**
Deploy a nix-bitcoin node and let it sync the blockchain. After a while the VirtualBox disk fills up an bitcoind crashes. (Where are the bitcoind logs located in nix-bitcoin? maybe add log locations to the FAQ?)

`df` shows a full disk using 100% of the 50GB defined in [https://github.com/NixOS/nixpkgs/nixos/modules/virtualisation/virtualbox-image.nix#L13](https://github.com/NixOS/nixpkgs/blob/d0bac7debccb6600cdda57c7242304d81655f8e6/nixos/modules/virtualisation/virtualbox-image.nix#L13)

**What doesn't work as a solution**
Adding `deployment.virtualbox.baseImageSize = 400 * 1024;` to `network/network-vbox.nix` doesn't work. Error thrown:

```
building all machine configurations...
error: The option `deployment.virtualbox.baseImageSize' defined in `/path/to/nix-bitcoin/network/network-vbox.nix' does not exist.
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/bin/..nixops-wrapped-wrapped", line 991, in <module>
    args.op()
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/bin/..nixops-wrapped-wrapped", line 412, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1052, in run_with_notify
    f()
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1063, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 1003, in _deploy
    self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
  File "/nix/store/fhhrm6nm71risrkp383nzdx1zviycfq6-nixops-1.7/lib/python2.7/site-packages/nixops/deployment.py", line 671, in build_configs
    raise Exception("unable to build all machine configurations")
Exception: unable to build all machine configurations
```

**Comment by jonasnick** [comment]
This doesn't work because `virtualbox.baseImageSize` is a NixOS option and not a NixOps option (i.e. it's only applicable if you create a virtual box in NixOS). I opened a PR with a fix.

**Comment by 0xB10C** [comment]
One solution would be to have e.g. a `vbox-resize.sh` script that:
1. stops the running VM
2. resizes the VDI with VBoxManage to a given (bigger) size 
3. starts the running VM
4. runs `fdisk -u /dev/sda` over ssh to create a bigger partition table 
5. runs `partx /dev/sda` or reboots the VM
6. runs `resize2fs /dev/sda1` to expand the file system

(see links in https://github.com/fort-nix/nix-bitcoin/pull/54#issuecomment-487512938 for more info)

**Comment by jonasnick** [comment]
Agree that this is a sensible solution. You don't have such a script in your shell history, have you? :)
