### ISSUE TITLE
yieldgenerator fails, wrong password / invalid padding byte after updating to v0.0.76

### ISSUE THREAD

**Issue by alumbigi** [fort-nix/nix-bitcoin#548]
started after upgrading to v0.0.76, issue remains after upgrading to v0.0.77

```
systemd[1]: Started joinmarket-yieldgenerator.service.
joinmarket-yieldgenerator[746892]: User data location: /var/lib/joinmarket
joinmarket-yieldgenerator[746892]: Traceback (most recent call last):
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/jmclient/storage.py", line 268, in _decrypt
joinmarket-yieldgenerator[746892]:     dec_data += decrypter.feed()
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/pyaes/blockfeeder.py", line 169, in feed
joinmarket-yieldgenerator[746892]:     result = self._final(self._buffer, self._padding)
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
joinmarket-yieldgenerator[746892]:     return strip_PKCS7_padding(self.decrypt(data))
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/pyaes/util.py", line 58, in strip_PKCS7_padding
joinmarket-yieldgenerator[746892]:     raise ValueError("invalid padding byte")
joinmarket-yieldgenerator[746892]: ValueError: invalid padding byte
joinmarket-yieldgenerator[746892]: During handling of the above exception, another exception occurred:
joinmarket-yieldgenerator[746892]: Traceback (most recent call last):
joinmarket-yieldgenerator[746892]:   File "/nix/store/d08c2qqz74xclz7h5605hx4ss3k4c905-joinmarket-0.9.7/bin/jm-yg-privacyenhanced", line 114, in <module>
joinmarket-yieldgenerator[746892]:     ygmain(YieldGeneratorPrivacyEnhanced, nickserv_password='')
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/jmclient/yieldgenerator.py", line 440, in ygmain
joinmarket-yieldgenerator[746892]:     wallet = open_test_wallet_maybe(
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/jmclient/wallet_utils.py", line 1502, in open_test_wallet_maybe
joinmarket-yieldgenerator[746892]:     return open_wallet(path, ask_for_password=False, password=password, mixdepth=max_mixdepth, **kwargs)
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/jmclient/wallet_utils.py", line 1547, in open_wallet
joinmarket-yieldgenerator[746892]:     storage = Storage(path, password, read_only=read_only)
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/jmclient/storage.py", line 99, in __init__
joinmarket-yieldgenerator[746892]:     self._load_file(password)
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/jmclient/storage.py", line 191, in _load_file
joinmarket-yieldgenerator[746892]:     data = self._decrypt_file(password, data)
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/jmclient/storage.py", line 253, in _decrypt_file
joinmarket-yieldgenerator[746892]:     return self._decrypt(container[b'data'], container[b'enc'][b'iv'])
joinmarket-yieldgenerator[746892]:   File "/nix/store/z079krn8g0sp083qmcbdgr8n650zn8k6-python3-3.9.13-env/lib/python3.9/site-packages/jmclient/storage.py", line 271, in _decrypt
joinmarket-yieldgenerator[746892]:     raise StoragePasswordError("Wrong password.")
joinmarket-yieldgenerator[746892]: jmclient.storage.StoragePasswordError: Wrong password.
systemd[1]: joinmarket-yieldgenerator.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: joinmarket-yieldgenerator.service: Failed with result 'exit-code'.
```

**Comment by erikarvstedt** [comment]
[Here's a branch](https://github.com/erikarvstedt/nix-bitcoin/commits/joinmarket-0.9.6) of the latest nix-bitcoin release (0.0.76) with the previous version of joinmarket (0.9.6).
Does this fix the bug for you?

**Comment by alumbigi** [comment]
stop/start services was not solving this but rebooting did -- closing
